name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to run CI against
        required: false
        default: main
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || inputs.ref }}
      - name: Prettier
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || inputs.ref }}
      - name: Prettier
        run: npm run test
  audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: NPM Audit
        run: npm audit
